# Generated by Django 4.1.7 on 2023-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url_trailer',
            field=models.SlugField(max_length=600),
        ),
    ]
